#!/bin/bash

ORANGE='\033[0;33m' 	# WARNINGS
RED='\033[0;31m'	# ERRORS
GREEN='\033[0;32m'	# COMPLETION
BLUE='\033[0;36m'	# FILES
PRP='\033[0;35m'	# COSMETIC
NC='\033[0m' # No Color

cores=4
source xenoseq_bin/functions.sh; 		# Simple custom-made functions to manipulate fasta files

print_usage() {
	  printf "Usage: ./xenoseq_prep -f1 forward_reads.fq -f2 reverse_reads.fq -o <output_filename> (-c NUM_CORES)\n"
  }


if [ "$#" -lt 2 ]; then
    print_usage;
	exit 1;
fi

while [ $# -gt 0 ]; do
	if [[ $1 =~ ^(-h|-help|--h|--help)$ ]] || [ -z "$1" ]; then
		print_usage;
	elif [[ $1 =~ ^(-f1|--f1|-forward|--forward)$ ]]; then
		f1=("$2")
	elif [[ $1 =~ ^(-f2|--f2|-reverse|--reverse)$ ]]; then
		f2=("$2")
	elif [[ $1 =~ ^(-o|--o|-output|--output)$ ]]; then
		output=("$2")
	elif [[ $1 =~ ^(-c|--cores)$ ]]; then
		cores=("$2")
	elif [[ $1 == *"-"* ]]; then	 # Capture any other flag in variable just in case
		v="${1/-/}"
		declare $v="$2"
	fi
	shift
done


mkdir -p $(dirname $output)
filename=$(basename -- "$output")
filename="${filename%.*}"

echo -en "[xenoseq_prep    $(date +%d-%m_%H:%M:%S)] FLASh... "
./xenoseq_bin/flash $f1 $f2 -o ${output}.flash -z -M 100 > ${output}.flash.log
echo -e "${GREEN}Done.${NC}"
zcat ${output}.flash.extendedFrags.fastq.gz ${output}.flash.notCombined_1.fastq.gz ${output}.flash.notCombined_2.fastq.gz > ${output}.flash.fq
echo -en "[xenoseq_prep    $(date +%d-%m_%H:%M:%S)] PRINSEQ-lite... "
perl xenoseq_bin/prinseq-lite.pl -fastq ${output}.flash.fq -out_format 1 -log -out_good ${output}.good -out_bad ${output}.bad -min_len 100 -min_qual_mean 25 -ns_max_p 10 -derep 14 2> ${output}.prinseq.log
echo -e "${GREEN}Done.${NC}"
echo -en "[xenoseq_prep    $(date +%d-%m_%H:%M:%S)] Verifying fasta headers... "
trimheaders ${output}.good.fasta 50 > ${output}.trimmed.fasta
makeidsuniq ${output}.trimmed.fasta > $(dirname $output)/${filename}_prepped.fasta
echo -e "${GREEN}Done.${NC}"

echo -e "[xenoseq_prep    $(date +%d-%m_%H:%M:%S)] ${GREEN}Preperation complete:${NC} $BLUE$(basename $f1)$NC + $BLUE$(basename $f2)$NC --> ${BLUE}$(dirname $output)/${filename}_prepped.fasta${NC}"
