name: xenoseq
channels:
  - bioconda
  - default
  - defaults
  - conda-forge
dependencies:
  - seqkit
  - megahit=1.2.9
  - parallel
  - fastp
  - bwa
  - samtools
  - blast
  - conda-forge::ncurses
