#!/bin/bash

ORANGE='\033[0;33m' 	# WARNINGS
RED='\033[0;31m'	# ERRORS
GREEN='\033[0;32m'	# COMPLETION
BLUE='\033[0;36m'	# FILES
PRP='\033[0;35m'	# COSMETIC
NC='\033[0m' # No Color

echo -e "Cleaning all example output"
rm -rf reads_prepped
rm -rf xenoseq_intermediates
rm -rf logs
rm -rf alignment_files
rm -rf xenoseq_results
rm -rf example_out
rm -rf xenoseq_benchmark
rm -rf output
rm -rf *.done
rm -rf *.fasta
echo -e "${GREEN}Done.${NC}"